### PR TITLE
Assets: General housekeeping on textures

### PR DESCRIPTION
**Pull request by loonaticx**
The following assets modified in this PR,

- Did not significantly change or alter how they look as seen in the application
- Were optimized using a tool called pngcrush to remove extraneous PNG chunks (Also stripped out any extraneous alpha channels which would theoretically improve texture memory usage)
- Converted to the nearest power of 2 resolution if not already
- Some textures were given texture margining/bleeding to provide support if they get downscaled via mipmapping or a texture quality setting.

### CODE REVIEW

**Comment by wyskoj** [comment]
This is great, thank you!!

The only issue is that the `sky.png` texture has lost its detail after being downscaled to 32x32. And I worry about scaling that texture because it will also scale when rendered. Perhaps it can still be pngcrushed without changing its scale?

**Review by wyskoj — CHANGES_REQUESTED** [review]
Can `sky.png` be optimized without changing it scale to preserve the detail?

**Comment by loonaticx** [comment]
> This is great, thank you!!
> 
> The only issue is that the `sky.png` texture has lost its detail after being downscaled to 32x32. And I worry about scaling that texture because it will also scale when rendered. Perhaps it can still be pngcrushed without changing its scale?

Fixed! Turns out when I rescaled the image it used a smooth resampling algorithm which removed the fine pixel details. Thought it had to do with transparency at first but my eyes were deceived 😛

**Review by wyskoj — CHANGES_REQUESTED** [review]
Something about the sky texture still isn't working right. It looks fine in an image editor, but when loading the app, the sky is a solid color. Perhaps it needs to be the next power of two larger? Or kept at 40x40? I think this is a jMonkeyEngine issue and not your fault because the texture looks fine to me.

**Comment by loonaticx** [comment]
For now I will keep the original sky texture file as-is; the asset itself has less of a performance concern than the others do.

**Review by wyskoj — APPROVED** [review]

**Comment by wyskoj** [comment]
Thanks @loonaticx for the contribution!

**Pull request merged**
