### PR TITLE
Add Russian i18n translation

### PR DESCRIPTION
**Pull request by rxuglr**

### CODE REVIEW

**Comment by rxuglr** [comment]
image
I did a test build and everything works fine

**Review by wyskoj — CHANGES_REQUESTED** [review]
Amazing!! Could you just delete the `Launcher.kt.bak` file? Then it should be perfect!

**Comment by rxuglr** [comment]
Yeah, sorry i forgot about this file. Deleted now

**Review by wyskoj — APPROVED** [review]

**Comment by wyskoj** [comment]
@rxuglr would you be willing to update your Russian translation? I'm hosting it at [POEditor](https://poeditor.com/join/project/alZE9e86Wd) now if you want to update it.

**Comment by rxuglr** [comment]
@wyskoj yeah, sure but it shows 100% for russian at POEditor..

**Pull request merged**
